/* Business Pulse: competitor intelligence for JD Meyers Productions.
   Reads window.PULSE_DATA from data/data.js (regenerated by the daily sync). No external libraries. */
(function(){
"use strict";

var D = window.PULSE_DATA;
var $ = function(s, r){ return (r||document).querySelector(s); };
var $$ = function(s, r){ return Array.prototype.slice.call((r||document).querySelectorAll(s)); };

if(!D){
  document.getElementById("main").innerHTML = '<div class="page-head"><h1>No data loaded</h1><p>data/data.js did not load. Check that the file exists in the repo and that the daily sync ran.</p></div>';
  return;
}

var FG = D.followGraph || {edges:[], status:{}, note:""};
var TOWNS = D.townCoords || {coords:{}, aliases:{}, unmappable:[]};
var JD_ACCOUNTS = ["jdmeyersproductions","jdmeyers_","fourierxform"];

/* ============================================================
   helpers
   ============================================================ */
function esc(s){ return String(s==null?"":s).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];}); }
function fmt(n){ return n==null||isNaN(n) ? "–" : Number(n).toLocaleString("en-US"); }
function money(n){ return n==null ? "–" : "$"+Number(n).toLocaleString("en-US"); }
function pct(x){ return x==null ? "–" : Math.round(x*100)+"%"; }
function parseDay(s){ if(!s) return null; var p=String(s).slice(0,10).split("-"); return new Date(+p[0],+p[1]-1,+p[2]); }
var NOW = (function(){ var g = D.meta && D.meta.generated_at ? new Date(D.meta.generated_at) : new Date(); return isNaN(g)?new Date():new Date(g.getFullYear(),g.getMonth(),g.getDate()); })();
function daysSince(s){ var d=parseDay(s); return d ? Math.round((NOW-d)/864e5) : null; }
var MON=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
function shortDate(s){ var d=parseDay(s); if(!d) return "–"; return MON[d.getMonth()]+" "+d.getDate()+(d.getFullYear()!==NOW.getFullYear()?", "+d.getFullYear():""); }
function ago(s){ var n=daysSince(s); if(n==null) return "no data"; if(n<=0) return "today"; if(n===1) return "yesterday"; if(n<60) return n+" days ago"; if(n<365) return Math.round(n/30)+" months ago"; return (n/365).toFixed(1)+" years ago"; }
function url(u){ if(!u) return null; return /^https?:\/\//.test(u)?u:"https://"+u; }
function uniq(a){ return a.filter(function(x,i){ return a.indexOf(x)===i; }); }
function median(a){ if(!a.length) return null; var s=a.slice().sort(function(x,y){return x-y;}); var m=Math.floor(s.length/2); return s.length%2?s[m]:Math.round((s[m-1]+s[m])/2); }
function norm(s){
  return String(s||"").toLowerCase().replace(/[’']/g,"").replace(/\([^)]*\)/g," ").replace(/&/g," ")
    .replace(/\b(photography|photographer|photos?|llc|studios?|productions?|media|services?|videography|video|films?|and|the|portrait|co)\b/g," ")
    .replace(/[^a-z0-9 ]/g," ").replace(/\s+/g," ").trim();
}
var reduceMotion = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;

/* ============================================================
   taxonomy: how the market is organized
   ============================================================ */
var LANES = [
  {id:"weddings",   label:"Weddings",            color:"var(--lane-weddings)",   hex:"#E4C9A6"},
  {id:"portraits",  label:"Portraits & family",  color:"var(--lane-portraits)",  hex:"#D595AE"},
  {id:"video",      label:"Video & film",        color:"var(--lane-video)",      hex:"#7FB2CE"},
  {id:"drone",      label:"Drone & real estate", color:"var(--lane-drone)",      hex:"#A99CE0"},
  {id:"commercial", label:"Commercial & niche",  color:"var(--lane-commercial)", hex:"#C9B870"},
  {id:"unclassified",label:"Not yet classified", color:"var(--lane-unclassified)",hex:"#5B6376"}
];
var LANE = {}; LANES.forEach(function(l){ LANE[l.id]=l; });
var LANE_PROMPT = { weddings:/wedding photographer/i, video:/videographer/i, drone:/drone/i, portraits:/family photographer/i };

var MOM = {
  entering:{label:"Entering", color:"var(--m-entering)", hex:"#8FD0F5", rank:0},
  active:  {label:"Active",   color:"var(--m-active)",   hex:"#EDEAE2", rank:1},
  quiet:   {label:"Quiet",    color:"var(--m-quiet)",    hex:"#7E879A", rank:2},
  fading:  {label:"Fading",   color:"var(--m-fading)",   hex:"#E27D6B", rank:3},
  unknown: {label:"No signal",color:"var(--m-unknown)",  hex:"#434A5B", rank:4}
};
var REGION = { slc:"St. Lawrence County", adjacent:"Neighboring counties", unconfirmed:"Location unconfirmed" };

function classifyLanes(c, price){
  var t = [c.name, c.notes, c.pricing, c.last_post_topic, (c.flags||[]).join(" ")].join(" ").toLowerCase()
    .replace(/not wedding[- ]focused|\(?not weddings\)?/g," ");
  var L = [];
  if(/wedding|elope|bride|knot|zola|weddingwire|\bmicro\b|\d\s?hr\b/.test(t) || c.specialty==="both" || (price && price.wedding)) L.push("weddings");
  if(/portrait|famil|senior|\bminis?\b|session|maternity|newborn|baby|children|couples|engagement|\bgrad\b/.test(t)) L.push("portraits");
  if(c.specialty==="video" || c.specialty==="both" || /\bvideo|\bfilms?\b/.test(String(c.name).toLowerCase())) L.push("video");
  if(c.specialty==="drone" || /drone|aerial|part-107/.test(t)) L.push("drone");
  if(/commercial|boudoir|booth|sports|real estate|brands|street photo|listing-video/.test(t)) L.push("commercial");
  if(!L.length) L.push("unclassified");
  return L;
}

/* ============================================================
   sweeps (website monitoring) lookup
   ============================================================ */
var SWEEPS = (D.webSweepHistory||[]).map(function(s,i){ s._i=i; return s; }).sort(function(a,b){ return a.date<b.date?-1:a.date>b.date?1:a._i-b._i; });
function sweepFor(c){
  var n = norm(c.name), idn = c.id.replace(/-/g," "), out = null;
  SWEEPS.forEach(function(s){
    Object.keys(s.pages||{}).forEach(function(k){
      var kn = norm(k.replace(/-/g," ").replace(/;$/,""));
      if(!kn) return;
      if(kn===n || n.indexOf(kn)===0 || idn.indexOf(k.replace(/-/g," ").toLowerCase())===0){
        out = {date:s.date, status:s.pages[k].status, note:s.pages[k].note, run:s.run_label};
      }
    });
  });
  return out;
}

/* ============================================================
   pricing
   ============================================================ */
function priceFloors(p){
  if(!p) return {wedding:null, session:null};
  var wedding=null, hourly=false, m = /wedding[^$;]*?\$([\d,]+)(\/hr)?/i.exec(p);
  if(m){ if(m[2]) hourly=true; else wedding=+m[1].replace(/,/g,""); }
  var re=/\$([\d,]+)/g, x, big=[], small=[];
  while((x=re.exec(p))){
    var v=+x[1].replace(/,/g,""), before=p.slice(Math.max(0,x.index-18),x.index).toLowerCase(), after=p.slice(x.index+x[0].length,x.index+x[0].length+10).toLowerCase();
    if(/deposit/.test(after) || /sports/.test(before) || /^\/(hr|event)/.test(after)) continue;
    (v>=1000?big:small).push(v);
  }
  if(wedding==null && !hourly && big.length) wedding=Math.min.apply(null,big);
  return {wedding:wedding, session: small.length?Math.min.apply(null,small):null, hourly:hourly};
}

/* ============================================================
   enrich the roster
   ============================================================ */
var IGH = D.igFollowersHistory || {};
var C = (D.competitors||[]).map(function(c){
  var e = Object.assign({}, c);
  e.price = priceFloors(c.pricing);
  e.lanes = classifyLanes(c, e.price);
  e.key = norm(c.name);
  var h = c.ig_handle && IGH[c.ig_handle];
  if(h && h.length){ e.followers = h[h.length-1].count; e.followHist = h; }
  else { var fm = /\((\d{1,3}(?:,\d{3})+|\d+), verified/.exec(c.notes||""); e.followers = fm ? +fm[1].replace(/,/g,"") : null; }
  e.postAge = daysSince(c.last_post_date);
  e.sweep = sweepFor(c);
  e.momentum = momentumOf(e);
  e.aiMentions = 0;
  return e;
});
var BY_ID = {}; C.forEach(function(c){ BY_ID[c.id]=c; });
var BY_KEY = {}; C.forEach(function(c){ if(c.key && !BY_KEY[c.key]) BY_KEY[c.key]=c; });
function findComp(name){
  var k = norm(name); if(BY_KEY[k]) return BY_KEY[k];
  var hit=null; C.forEach(function(c){ if(!hit && k && (c.key.indexOf(k)===0 || k.indexOf(c.key)===0) && Math.min(k.length,c.key.length)>=6) hit=c; });
  return hit;
}

function momentumOf(c){
  var f = c.flags||[], n=(c.notes||"").toLowerCase(), sw=c.sweep;
  function has(re){ return f.some(function(x){ return re.test(x); }); }
  if(has(/^new-entrant/)) return {k:"entering", why:"Newly entered the market ("+shortDate(String(f.filter(function(x){return /^new-entrant/.test(x);})[0]).replace("new-entrant-",""))+")."+(has(/relocating-from/)?" Relocating into the area.":"")};
  if(has(/relocating-from/)) return {k:"entering", why:"Relocating into the area."};
  if(/est\.\s?202[4-9]/.test(n)) return {k:"entering", why:"Established recently ("+(/est\.\s?(20\d\d)/.exec(n)||[])[1]+")."};
  if(sw && /closed/i.test(sw.note||"")) return {k:"fading", why:"Website says: "+sw.note+"."};
  if(has(/stepping-back/)) return {k:"fading", why:"Owner is stepping back from new work."};
  if(has(/website-dead/)) return {k:"fading", why:"Website is dead; Instagram still exists."};
  if(has(/bio-dormant/)) return {k:"fading", why:"Instagram bio says they are off the platform."};
  if(has(/site-closure/)) return {k:"fading", why:"Website announced a closure; social is mixed."};
  if(has(/late-career/)) return {k:"fading", why:"Late-career, maintenance mode."};
  if(/relocation planned|announced .{0,20}relocation/.test(n)) return {k:"fading", why:"Announced a move out of the area."};
  if(/(account|ig)[^.;]{0,20}(inactive|dormant)/.test(n)) return {k:"fading", why:"Instagram looks dormant."};
  if(c.postAge!=null && c.postAge>180) return {k:"fading", why:"No Instagram post in "+Math.round(c.postAge/30)+" months."};
  if(c.postAge!=null && c.postAge<=21) return {k:"active", why:"Posted "+ago(c.last_post_date)+(c.last_post_topic?": "+c.last_post_topic:"")+"."};
  if(c.postAge!=null) return {k:"quiet", why:"Last post "+ago(c.last_post_date)+"."};
  if(c.status==="uncertain") return {k:"fading", why:"Status uncertain on the roster."};
  return {k:"unknown", why:"No activity data yet. Needs an Instagram handle or a working website to track."};
}

/* ============================================================
   discovery hubs: where each competitor came from
   ============================================================ */
var HUBS = {};
function hub(id, o){ if(!HUBS[id]) HUBS[id] = Object.assign({id:id, spokes:[]}, o); return HUBS[id]; }
C.forEach(function(c){
  var n = c.notes||"", m = /spotted in (.+?)(?:'s|’s|') IG following/i.exec(n), h;
  if(m){
    var seed = findComp(m[1]);
    h = seed ? hub("ig:"+seed.id, {label:seed.name.replace(/ \(.*\)/,"")+"’s following", kind:"Instagram following", seed:seed.id, desc:"Businesses found by reading who "+seed.name+" follows on Instagram."})
             : hub("ig:"+norm(m[1]), {label:m[1]+"’s following", kind:"Instagram following", desc:"Found in "+m[1]+"’s Instagram following."});
  } else if(/round-3 IG trawl/i.test(n) || c.source_label==="Instagram"){
    h = hub("trawl", {label:"Instagram trawl", kind:"Search sweep", desc:"Round-3 sweep of North Country wedding and portrait accounts on Instagram."});
  } else if(/Luna discovery/i.test(n) || c.source_label==="AI audit"){
    h = hub("ai", {label:"AI engine audit", kind:"AI discovery", desc:"Names surfaced by asking ChatGPT, Claude, Gemini and Perplexity who to hire, then verified."});
  } else if((c.flags||[]).some(function(f){return /^new-entrant/.test(f);})){
    h = hub("sweep", {label:"Daily sweep", kind:"Automated discovery", desc:"New entrants picked up by the daily website and directory sweep."});
  } else if(c.source==="web-audit-may2026" || c.source_label==="Web search"){
    h = hub("web", {label:"Web audit, May 2026", kind:"Search audit", desc:"The original Google search audit of local wedding and portrait photographers."});
  } else {
    h = hub("roster", {label:"Initial roster", kind:"Directory build", desc:"Built from directories, Google listings, The Knot, Zola and JD’s own knowledge."});
  }
  h.spokes.push(c.id); c.hub = h.id;
});
var HUB_LIST = Object.keys(HUBS).map(function(k){ return HUBS[k]; }).sort(function(a,b){ return (b.seed?1:0)-(a.seed?1:0) || b.spokes.length-a.spokes.length; });

/* ============================================================
   relationships: collaborations, sister accounts, ties to JD
   ============================================================ */
var EXT = {};  // outside businesses that appear only in collaborations
var LINKS = [];
function endpoint(name){
  var c = findComp(name); if(c) return c.id;
  var id = "ext:"+norm(name).replace(/ /g,"-");
  if(!EXT[id]) EXT[id] = {id:id, name:name.replace(/ \(.*\)/,""), links:[]};
  return id;
}
(D.connections||[]).forEach(function(x){
  var a=endpoint(x.a), b=endpoint(x.b);
  var l={s:a, t:b, type:"collab", sub:x.type, date:x.date, evidence:x.evidence};
  LINKS.push(l); if(EXT[a]) EXT[a].links.push(l); if(EXT[b]) EXT[b].links.push(l);
});
C.forEach(function(c){
  var m = /sister [a-z ]*account of ([^;]+)/i.exec(c.notes||"");
  if(m){ var o=findComp(m[1]); if(o && o.id!==c.id) LINKS.push({s:c.id,t:o.id,type:"sister",sub:"same business",evidence:"Sister account of "+o.name+"; same business and pricing."}); }
  var f=c.flags||[];
  if(f.indexOf("vouched-by-jd")>=0) LINKS.push({s:"jd",t:c.id,type:"jd",sub:"vouched by JD",evidence:"JD knows this business personally and vouches for it."});
  if(f.indexOf("mutual-ig-follows-jd")>=0) LINKS.push({s:"jd",t:c.id,type:"jd",sub:"mutual follow",evidence:"Follows JD on Instagram and JD follows back."});
});
function linksOf(id){ return LINKS.filter(function(l){ return l.s===id || l.t===id; }); }
function nameOf(id){
  if(id==="jd") return "JD Meyers Productions";
  if(BY_ID[id]) return BY_ID[id].name;
  if(EXT[id]) return EXT[id].name;
  if(HUBS[id]) return HUBS[id].label;
  return id;
}
var SUB_LABEL = {"co-tagged":"Co-tagged on a post","second-shooter":"Second shooter","styled-shoot":"Creative collab","same business":"Same business","vouched by JD":"Vouched by JD","mutual follow":"Mutual follow"};

/* ============================================================
   AI visibility
   ============================================================ */
var AI = D.aiVisibility||[];
var RUN_ORDER = {"baseline":0,"daily":1,"daily-midday":2,"daily-evening":3};
var RUN_LABEL = {"baseline":"baseline","daily":"morning","daily-midday":"midday","daily-evening":"evening"};
var RUN_SHORT = {"baseline":"base","daily":"am","daily-midday":"mid","daily-evening":"pm"};
var RUNS = (function(){
  var m={};
  AI.forEach(function(r){ var k=r.date+"|"+(RUN_ORDER[r.run]!=null?RUN_ORDER[r.run]:9)+"|"+r.run; (m[k]=m[k]||{key:k,date:r.date,run:r.run,rows:[]}).rows.push(r); });
  return Object.keys(m).sort().map(function(k){ var r=m[k]; r.label=shortDate(r.date)+" "+(RUN_LABEL[r.run]||r.run); var d=parseDay(r.date); r.tick=(d.getMonth()+1)+"/"+d.getDate()+" "+(RUN_SHORT[r.run]||r.run); return r; });
})();
var ENGINES = uniq(AI.map(function(r){ return r.engine; }));
var PROMPTS = uniq(AI.map(function(r){ return r.prompt; }));
function score(v){ return v==="yes"?1:v==="partial"?.5:v==="no"?0:null; }
function rate(rows){ var s=0,n=0; rows.forEach(function(r){ var v=score(r.jd_named); if(v!=null){ s+=v; n++; } }); return n?s/n:null; }
var LAST_RUN = RUNS[RUNS.length-1];
var FIRST_RUN = RUNS[0];
function laneAI(lane){
  var re = LANE_PROMPT[lane]; if(!re || !LAST_RUN) return null;
  return rate(LAST_RUN.rows.filter(function(r){ return re.test(r.prompt); }));
}
// who the AI engines recommend, on the most recent day
var RIVALS = (function(){
  if(!LAST_RUN) return [];
  var day = LAST_RUN.date, counts={}, prompts={};
  AI.filter(function(r){ return r.date===day; }).forEach(function(r){
    var ans=r.date+r.run+r.engine;
    uniq(r.rivals||[]).forEach(function(n){ var k=norm(n)||n; if(!counts[k]) counts[k]={name:n,n:0,engines:{},seen:{}}; if(!counts[k].seen[ans]){ counts[k].seen[ans]=1; counts[k].n++; } counts[k].engines[r.engine]=1; });
  });
  var exKeys = (D.excluded||[]).map(function(x){ return {k:norm(x.name), x:x}; });
  return Object.keys(counts).map(function(k){
    var o=counts[k], c=findComp(o.name), ex=null;
    exKeys.forEach(function(e){ if(!ex && e.k && (e.k===k || (k.indexOf(e.k)===0 && e.k.length>=6))) ex=e.x; });
    o.comp=c; o.excluded=!c?ex:null; o.status=c?"roster":ex?"excluded":"blind"; o.engineCount=Object.keys(o.engines).length;
    return o;
  }).sort(function(a,b){ return b.n-a.n || a.name.localeCompare(b.name); });
})();
// all-time AI mentions per roster competitor
(function(){ var seen={}; AI.forEach(function(r){ var ans=r.date+r.run+r.engine; uniq(r.rivals||[]).forEach(function(n){ var c=findComp(n); if(c && !seen[c.id+ans]){ seen[c.id+ans]=1; c.aiMentions++; } }); }); })();

/* ============================================================
   derived summaries
   ============================================================ */
function laneStats(id){
  var list = C.filter(function(c){ return c.lanes.indexOf(id)>=0; });
  var m = {entering:0,active:0,quiet:0,fading:0,unknown:0};
  list.forEach(function(c){ m[c.momentum.k]++; });
  var wf = list.map(function(c){ return c.price.wedding; }).filter(function(v){ return v!=null; });
  var sf = list.map(function(c){ return c.price.session; }).filter(function(v){ return v!=null; });
  return {id:id, list:list, n:list.length, mom:m, net:m.entering-m.fading, wMed:median(wf), sMed:median(sf), wN:wf.length, sN:sf.length, home:list.filter(function(c){return c.region==="slc";}).length, ai:laneAI(id)};
}
var LSTATS = {}; LANES.forEach(function(l){ LSTATS[l.id]=laneStats(l.id); });
var MOMCOUNT = {entering:0,active:0,quiet:0,fading:0,unknown:0}; C.forEach(function(c){ MOMCOUNT[c.momentum.k]++; });
var OWN = (function(){ var m={}; (D.ownAccounts||[]).forEach(function(r){ if(!m[r.account] || r.date>m[r.account].date) m[r.account]=r; }); return m; })();

/* ============================================================
   navigation
   ============================================================ */
var VIEWS = [
  {id:"pulse",   label:"Pulse"},
  {id:"network", label:"Follow graph", count:function(){ return FG.edges.length+" links"; }},
  {id:"map", label:"Map"},
  {id:"roster",  label:"Roster",  count:function(){ return C.length; }},
  {id:"market",  label:"Market lanes"},
  {id:"ai",      label:"AI visibility"},
  {sep:true},
  {id:"sweeps",  label:"Website sweeps", count:function(){ return SWEEPS.length; }},
  {id:"intake",  label:"Add competitor"}
];
var RENDER = {}, rendered = {};
function buildNav(){
  $("#nav").innerHTML = VIEWS.map(function(v){
    if(v.sep) return '<div class="sep" role="presentation"></div>';
    return '<a href="#/'+v.id+'" data-v="'+v.id+'">'+esc(v.label)+(v.count?'<span>'+esc(v.count())+'</span>':"")+'</a>';
  }).join("");
  var gen = D.meta && D.meta.generated_at ? new Date(D.meta.generated_at) : null;
  $("#freshness").innerHTML = '<span class="live-dot"></span>Synced <b>'+(gen&&!isNaN(gen)?gen.toLocaleDateString("en-US",{month:"short",day:"numeric"})+", "+gen.toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"}):"unknown")+'</b><br>Refreshes each morning after the digest.';
}
function route(){
  var id = (location.hash.replace(/^#\/?/,"").split("/")[0]) || "pulse";
  if(!RENDER[id]) id="pulse";
  $$(".view").forEach(function(v){ v.classList.toggle("on", v.id==="view-"+id); });
  $$("#nav a").forEach(function(a){ if(a.dataset.v===id) a.setAttribute("aria-current","page"); else a.removeAttribute("aria-current"); });
  if(!rendered[id]){ RENDER[id]($("#view-"+id)); rendered[id]=true; }
  if(id==="network" && NET) NET.wake();
  window.scrollTo(0,0);
}
function go(id){ location.hash = "#/"+id; }

/* shared little renderers */
function momBadge(c){ var m=MOM[c.momentum.k]; return '<span class="mom" style="--c:'+m.color+'"><i></i>'+m.label+'</span>'; }
function laneTags(c){ return c.lanes.map(function(l){ return '<span class="tag lane" style="--c:'+LANE[l].color+'">'+esc(LANE[l].label)+'</span>'; }).join(""); }
function chipFor(id){
  var c = BY_ID[id];
  if(c) return '<button class="chip" data-open="'+esc(id)+'" style="--d:'+MOM[c.momentum.k].color+'"><span class="dot"></span>'+esc(c.name.replace(/ \(.*\)/,""))+'</button>';
  return '<button class="chip" data-open="'+esc(id)+'"><span class="dot"></span>'+esc(nameOf(id))+'</button>';
}
function arrow(dir){
  if(dir>0) return '<svg viewBox="0 0 14 14" aria-hidden="true"><path d="M3 10 L11 3 M6 3 H11 V8" stroke="currentColor" stroke-width="1.8" fill="none" stroke-linecap="round"/></svg>';
  if(dir<0) return '<svg viewBox="0 0 14 14" aria-hidden="true"><path d="M3 4 L11 11 M11 6 V11 H6" stroke="currentColor" stroke-width="1.8" fill="none" stroke-linecap="round"/></svg>';
  return '<svg viewBox="0 0 14 14" aria-hidden="true"><path d="M2 7 H12" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>';
}
function dirLabel(s){
  if(s.net>0) return '<span class="dir up">'+arrow(1)+'Growing</span>';
  if(s.net<0) return '<span class="dir down">'+arrow(-1)+'Thinning</span>';
  return '<span class="dir flat">'+arrow(0)+'Holding</span>';
}
function mixBar(m, total){
  if(!total) return "";
  return '<div class="mix" title="'+Object.keys(MOM).map(function(k){return MOM[k].label+": "+m[k];}).join(", ")+'">'+
    Object.keys(MOM).map(function(k){ return m[k]?'<i style="width:'+(m[k]/total*100)+'%;background:'+MOM[k].color+'"></i>':""; }).join("")+'</div>';
}

/* ============================================================
   PULSE (home)
   ============================================================ */
RENDER.pulse = function(el){
  var active30 = C.filter(function(c){ return c.postAge!=null && c.postAge<=30; }).length;
  var jdNow = LAST_RUN?rate(LAST_RUN.rows):null, jdThen = FIRST_RUN?rate(FIRST_RUN.rows):null;
  var blind = RIVALS.filter(function(r){ return r.status==="blind"; });
  var noPrice = C.filter(function(c){ return !c.pricing; }).length;
  var noTrack = C.filter(function(c){ return c.momentum.k==="unknown"; }).length;
  var home = C.filter(function(c){ return c.region==="slc"; }).length;
  var topHub = HUB_LIST.filter(function(h){return h.seed;}).sort(function(a,b){return b.spokes.length-a.spokes.length;})[0];
  var busiest = LANES.filter(function(l){return l.id!=="unclassified";}).map(function(l){ var s=LSTATS[l.id]; return {l:l, a:s.list.filter(function(c){return c.momentum.k==="active";}).length}; }).sort(function(a,b){return b.a-a.a;})[0];
  var wMed = LSTATS.weddings.wMed;

  var lede = 'Watching <em>'+C.length+' businesses</em> across the North Country. '+
    (MOMCOUNT.entering?MOMCOUNT.entering+' entering, ':'')+MOMCOUNT.fading+' fading, and JD is named in <em>'+pct(jdNow)+'</em> of AI recommendations'+(jdThen!=null&&jdNow!=null&&Math.round(jdNow*100)!==Math.round(jdThen*100)?(jdNow>jdThen?', up from ':', down from ')+pct(jdThen)+' at baseline':'')+'.';

  var points = [
    {c:"var(--m-active)", h:'<b>'+active30+' competitors posted in the last 30 days.</b> '+(busiest?'The busiest lane right now is '+esc(busiest.l.label.toLowerCase())+' ('+busiest.a+' active).':'')},
    wMed?{c:"var(--lane-weddings)", h:'<b>Wedding coverage starts around '+money(wMed)+'</b> (median of '+LSTATS.weddings.wN+' published starting prices).'}:null,
    topHub?{c:"var(--lane-video)", h:'<b>'+esc(topHub.label)+' surfaced '+topHub.spokes.length+' competitors.</b> One Instagram account is currently your best map of the wedding scene.'}:null,
    blind.length?{c:"var(--amber)", h:'<b>'+blind.length+' businesses AI recommends are not on your roster.</b> Those are blind spots worth a look.'}:null,
    {c:"var(--m-quiet)", h:'<b>Research gaps:</b> '+noPrice+' have no published pricing and '+noTrack+' have no trackable activity yet.'}
  ].filter(Boolean);

  var h = '<div class="reveal">';
  h += '<div class="grid g-hero" style="margin-bottom:18px">';
  h += '<div class="brief"><div class="date">'+NOW.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"})+'</div><p class="lede">'+lede+'</p><ul class="points">'+
       points.map(function(p){ return '<li style="--dot:'+p.c+'">'+p.h+'</li>'; }).join("")+'</ul></div>';
  // right column: JD AI gauge + market mix
  h += '<div class="stack">';
  h += '<div class="panel gauge"><div class="row-between"><h2>JD in AI answers</h2><button class="linkish" data-go="ai">Details</button></div>'+
       '<div class="big num">'+(jdNow==null?"–":Math.round(jdNow*100))+'<small>%</small></div>'+
       '<div class="muted" style="font-size:13.5px">Share of prompts where ChatGPT, Claude, Gemini or Perplexity named JD in the latest run ('+esc(LAST_RUN?LAST_RUN.label:"none")+').</div>'+
       '<div class="chart" id="pulseSpark"></div></div>';
  h += '<div class="panel"><h2>Market momentum</h2><p class="hint" style="margin-bottom:12px">Every tracked business, by what it is doing right now.</p>'+
       '<div class="mix" style="height:12px;margin-bottom:14px">'+Object.keys(MOM).map(function(k){ return MOMCOUNT[k]?'<i style="width:'+(MOMCOUNT[k]/C.length*100)+'%;background:'+MOM[k].color+'"></i>':""; }).join("")+'</div>'+
       '<div class="chips">'+Object.keys(MOM).map(function(k){ return '<button class="chip" data-mom="'+k+'" style="--d:'+MOM[k].color+'"><span class="dot"></span>'+MOM[k].label+' '+MOMCOUNT[k]+'</button>'; }).join("")+'</div></div>';
  h += '</div></div>';

  // lane board
  h += '<div class="panel" style="margin-bottom:18px"><div class="row-between"><h2>Direction by lane</h2><span class="muted" style="font-size:13px">Click a lane to open it</span></div>'+
       '<p class="hint">A business can sit in more than one lane. Direction compares businesses entering against those fading.</p><div class="tablewrap"><table class="lanes"><thead><tr>'+
       '<th>Lane</th><th>Tracked</th><th class="hide-sm">In St. Lawrence</th><th>Momentum</th><th>Direction</th><th class="hide-sm">Typical start</th><th>JD in AI</th></tr></thead><tbody>';
  LANES.forEach(function(l){
    var s=LSTATS[l.id]; if(!s.n) return;
    var typical = l.id==="weddings"||l.id==="video" ? (s.wMed?money(s.wMed):"–") : l.id==="unclassified" ? "–" : (s.sMed?money(s.sMed)+" session":"–");
    h += '<tr class="lane-row" data-lane="'+l.id+'" tabindex="0"><td><span class="lane-name"><span class="swatch" style="--c:'+l.color+'"></span>'+esc(l.label)+'</span></td>'+
         '<td class="num">'+s.n+'</td><td class="num hide-sm">'+s.home+'</td><td>'+mixBar(s.mom,s.n)+'</td><td>'+(l.id==="unclassified"?'<span class="muted" style="font-size:13px">Needs research</span>':dirLabel(s))+'</td>'+
         '<td class="num hide-sm">'+typical+'</td><td>'+(s.ai==null?'<span class="muted">not tracked</span>':'<span class="meter"><i style="width:'+Math.round(s.ai*100)+'%"></i></span><span class="num">'+pct(s.ai)+'</span>')+'</td></tr>';
  });
  h += '</tbody></table></div></div>';

  // movement + audience
  h += '<div class="grid g-2">';
  h += '<div class="panel"><h2>Movement</h2><p class="hint">What changed most recently, newest first.</p><ul class="feed">'+movementFeed()+'</ul></div>';
  h += '<div class="stack"><div class="panel"><h2>Instagram reach</h2><p class="hint">JD’s accounts against tracked competitors with follower counts.</p><div class="bars">'+audienceBars()+'</div></div>'+
       '<div class="panel"><h2>Where they are</h2><p class="hint">'+home+' of '+C.length+' are based in St. Lawrence County.</p><div class="bars">'+countyBars()+'</div></div></div>';
  h += '</div></div>';
  el.innerHTML = h;
  drawSpark($("#pulseSpark"));
};

function movementFeed(){
  var ev=[];
  var byDay={};
  C.forEach(function(c){ if(c.discovered_date){ (byDay[c.discovered_date]=byDay[c.discovered_date]||[]).push(c.id); } });
  Object.keys(byDay).forEach(function(d){
    var ids=byDay[d], newc=ids.filter(function(id){ return BY_ID[id].momentum.k==="entering"; });
    if(newc.length) ev.push({d:d, k:"New to market", c:"var(--m-entering)", h:'<b>'+newc.length+(newc.length>1?' new businesses':' new business')+'</b> started taking work locally.', chips:newc});
    var rest=ids.filter(function(id){ return newc.indexOf(id)<0; });
    if(rest.length) ev.push({d:d, k:"Added to watch", c:"var(--lane-video)", h:'<b>'+rest.length+' businesses</b> added to the roster.', chips:rest});
  });
  C.filter(function(c){ return c.postAge!=null && c.postAge<=10; }).forEach(function(c){
    ev.push({d:c.last_post_date, k:"Posted", c:"var(--m-active)", h:'<b>'+esc(c.name)+'</b>'+(c.last_post_topic?': '+esc(c.last_post_topic):''), open:c.id});
  });
  (D.igActivity||[]).forEach(function(r){
    if(/^quiet/i.test(r.activity) || !/active|posts?|burst/i.test(r.activity) || /^last post/i.test(r.activity)) return;
    var c=C.filter(function(x){return x.ig_handle===r.handle;})[0];
    ev.push({d:r.date, k:"Instagram", c:"var(--lane-portraits)", h:'<b>'+esc(c?c.name:"@"+r.handle)+'</b>: '+esc(r.activity), open:c&&c.id});
  });
  SWEEPS.forEach(function(s){ var rc=s.roster_corrections||[]; if(rc.length) ev.push({d:s.date, k:"Corrections", c:"var(--m-quiet)", h:'<b>'+rc.length+' roster '+(rc.length>1?'corrections':'correction')+'</b>: '+rc.map(esc).join("; ")+'.'}); });
  C.filter(function(c){ return c.momentum.k==="fading" && c.sweep && /closed/i.test(c.sweep.note||""); }).forEach(function(c){
    ev.push({d:c.sweep.date, k:"Closed", c:"var(--m-fading)", h:'<b>'+esc(c.name)+'</b>: '+esc(c.sweep.note), open:c.id});
  });
  ev.sort(function(a,b){ return a.d<b.d?1:a.d>b.d?-1:0; });
  return ev.slice(0,12).map(function(e){
    return '<li><div class="when">'+shortDate(e.d)+'</div><div class="what"><span class="kind" style="--k:'+e.c+'">'+e.k+'</span>'+
      (e.open?'<button class="linkish" data-open="'+esc(e.open)+'" style="text-decoration:none;color:inherit;text-align:left">'+e.h+'</button>':e.h)+
      (e.chips?'<div class="chips">'+e.chips.slice(0,14).map(chipFor).join("")+(e.chips.length>14?'<span class="muted" style="font-size:12.5px;align-self:center">+'+(e.chips.length-14)+' more</span>':'')+'</div>':'')+
      '</div></li>';
  }).join("") || '<li class="empty">No movement recorded yet.</li>';
}
function audienceBars(){
  var rows=[];
  Object.keys(OWN).forEach(function(a){ rows.push({n:"@"+a, v:OWN[a].follower_count, jd:true}); });
  C.filter(function(c){return c.followers;}).forEach(function(c){ rows.push({n:c.name.replace(/ \(.*\)/,""), v:c.followers, id:c.id}); });
  rows.sort(function(a,b){return b.v-a.v;});
  var top = rows.filter(function(r){return !r.jd;}).slice(0,7).concat(rows.filter(function(r){return r.jd;})).sort(function(a,b){return b.v-a.v;});
  var max = Math.max.apply(null, top.map(function(r){return r.v;}));
  return top.map(function(r){
    return '<div class="bar'+(r.jd?' jd':'')+'"><span class="n"'+(r.id?' data-open="'+r.id+'"':'')+'>'+esc(r.n)+'</span><span class="t"><i style="width:'+(r.v/max*100)+'%;--c:'+(r.jd?'var(--amber)':'var(--silver-2)')+'"></i></span><span class="v">'+fmt(r.v)+'</span></div>';
  }).join("");
}
function countyBars(){
  var m={}; C.forEach(function(c){ var k=c.county && c.county!=="unknown" ? c.county : "Unconfirmed"; m[k]=(m[k]||0)+1; });
  var rows=Object.keys(m).map(function(k){return {n:k,v:m[k]};}).sort(function(a,b){ return (a.n==="Unconfirmed")-(b.n==="Unconfirmed") || b.v-a.v; });
  var max=Math.max.apply(null,rows.map(function(r){return r.v;}));
  return rows.map(function(r){ return '<div class="bar"><span class="n" data-county="'+esc(r.n)+'">'+esc(r.n)+'</span><span class="t"><i style="width:'+(r.v/max*100)+'%;--c:'+(r.n==="St. Lawrence"?'var(--amber)':'var(--line-2)')+'"></i></span><span class="v">'+r.v+'</span></div>'; }).join("");
}

/* small SVG line chart */
function lineChart(series, opts){
  opts=opts||{}; var W=opts.w||560, H=opts.h||200, pl=36, pr=12, pt=10, pb=opts.labels?34:12;
  var n = Math.max.apply(null, series.map(function(s){return s.values.length;}));
  function X(i){ return n<=1?pl+(W-pl-pr)/2:pl+i*(W-pl-pr)/(n-1); }
  function Y(v){ return pt+(1-v)*(H-pt-pb); }
  var g='';
  [0,.25,.5,.75,1].forEach(function(t){ g+='<line class="gridl" x1="'+pl+'" x2="'+(W-pr)+'" y1="'+Y(t)+'" y2="'+Y(t)+'"/><text x="'+(pl-8)+'" y="'+(Y(t)+4)+'" text-anchor="end">'+Math.round(t*100)+'%</text>'; });
  if(opts.labels) opts.labels.forEach(function(l,i){ if(n>10 && i%2 && i!==n-1) return; g+='<text x="'+X(i)+'" y="'+(H-8)+'" text-anchor="middle">'+esc(l)+'</text>'; });
  series.forEach(function(s){
    var pts=[]; s.values.forEach(function(v,i){ if(v!=null) pts.push([X(i),Y(v),v,i]); });
    if(pts.length>1) g+='<path d="M'+pts.map(function(p){return p[0].toFixed(1)+","+p[1].toFixed(1);}).join(" L")+'" fill="none" stroke="'+s.color+'" stroke-width="'+(s.w||2)+'" stroke-linejoin="round" stroke-linecap="round"/>';
    pts.forEach(function(p){ g+='<circle cx="'+p[0]+'" cy="'+p[1]+'" r="3" fill="'+s.color+'"><title>'+esc(s.name+": "+Math.round(p[2]*100)+"%"+(opts.labels?" ("+opts.labels[p[3]]+")":""))+'</title></circle>'; });
  });
  return '<svg viewBox="0 0 '+W+' '+H+'" role="img" aria-label="'+esc(opts.aria||"line chart")+'">'+g+'</svg>';
}
function drawSpark(el){
  if(!el || !RUNS.length) return;
  el.innerHTML = lineChart([{name:"All engines", color:"#E7A04F", w:2.5, values:RUNS.map(function(r){return rate(r.rows);})}], {w:420,h:120,aria:"JD named rate over runs"});
}

/* ============================================================
   FOLLOW GRAPH: who follows who on Instagram (verified edges only)
   ============================================================ */
function normHandle(h){ return String(h||"").toLowerCase().replace(/^@/,"").trim(); }
var FGN = (function(){
  var nodes=[], byKey={};
  function add(n){ if(!byKey[n.key]){ byKey[n.key]=n; nodes.push(n); } return byKey[n.key]; }
  JD_ACCOUNTS.forEach(function(u){ add({key:"jd:"+u, kind:"jd", label:"@"+u, handle:u}); });
  C.forEach(function(c){ if(c.ig_handle) add({key:"ig:"+normHandle(c.ig_handle), kind:"comp", label:c.name.replace(/ \(.*\)/,""), comp:c, handle:normHandle(c.ig_handle)}); });
  function keyOf(e){ var h=normHandle(e); return JD_ACCOUNTS.indexOf(h)>=0 ? "jd:"+h : "ig:"+h; }
  var pairs={}, follows={}, followedBy={};
  (FG.edges||[]).forEach(function(e){
    var a=keyOf(e.from), b=keyOf(e.to);
    if(!byKey[a]||!byKey[b]||a===b) return;
    (follows[a]=follows[a]||[]).push(b);
    (followedBy[b]=followedBy[b]||[]).push(a);
    var k=[a,b].sort().join("|");
    var p=pairs[k]||(pairs[k]={a:a,b:b,mutual:false});
    if((follows[b]||[]).indexOf(a)>=0) p.mutual=true;
  });
  nodes.forEach(function(n){
    n.follows=(follows[n.key]||[]).map(function(k){return byKey[k];});
    n.followedBy=(followedBy[n.key]||[]).map(function(k){return byKey[k];});
    n.deg=n.follows.length+n.followedBy.length;
  });
  return {nodes:nodes, byKey:byKey, pairs:Object.keys(pairs).map(function(k){return pairs[k];})};
})();

var NET = null;
RENDER.network = function(el){
  var P=FGN.pairs, nodes=FGN.nodes;
  var h='<div class="page-head"><h1>Who follows who</h1><p>Verified Instagram follow links between the roster and JD\u2019s accounts \u2014 nothing else. One line per pair; click any name for the direction. Competitor-to-competitor links are not mapped yet \u2014 they need a logged-in Instagram check.</p></div>';
  h+='<div class="net-wrap" id="netWrap"><svg id="netSvg" viewBox="0 0 940 720" role="img" aria-label="Instagram follow graph"><g id="netEdges"></g><g id="netNodes"></g></svg>'+
     '<div class="net-legend"><span><span class="ln" style="--c:#8fa3c8"></span>Follow link</span><span><span class="ln" style="--c:#d7e2f7;border-top-width:3px"></span>Mutual</span><span><span class="swatch" style="--c:var(--amber);border-radius:50%"></span>JD\u2019s accounts</span><span><span class="swatch" style="--c:#8fa3c8;border-radius:50%"></span>Competitor</span><span>'+P.length+' verified links</span></div></div>';
  h+='<div class="panel" style="margin-top:18px"><h2>Follow details</h2><p class="hint">Click a name on the graph.</p><div id="fgDetail"><p class="muted">No one selected yet.</p></div></div>';
  h+='<div class="panel"><h2>Collaborations and ties</h2><p class="hint">Evidence of businesses working together \u2014 kept as a plain list, separate from the follow graph.</p><div class="tablewrap"><table class="data"><thead><tr><th>Between</th><th>Relationship</th><th>When</th><th>Evidence</th></tr></thead><tbody>';
  LINKS.slice().sort(function(a,b){ return (a.type==="jd")-(b.type==="jd") || String(b.date||"").localeCompare(String(a.date||"")); }).forEach(function(l){
    h+='<tr data-open="'+esc(l.s==="jd"?l.t:l.s)+'"><td class="nm">'+esc(nameOf(l.s))+'<small>with '+esc(nameOf(l.t))+'</small></td><td>'+esc(SUB_LABEL[l.sub]||l.sub)+'</td><td class="num">'+(l.date?shortDate(l.date):'<span class="muted">undated</span>')+'</td><td class="muted" style="max-width:520px">'+esc(l.evidence||"")+'</td></tr>';
  });
  h+='</tbody></table></div></div>';
  el.innerHTML=h;
  NET=buildFollowGraph();
};

function buildFollowGraph(){
  var wrap=$("#netWrap"), gE=$("#netEdges"), gN=$("#netNodes");
  var NS="http://www.w3.org/2000/svg";
  var CX=470, CY=350;
  var nodes=FGN.nodes, byKey=FGN.byKey;
  var jd=nodes.filter(function(n){return n.kind==="jd";});
  var linked=nodes.filter(function(n){return n.kind==="comp"&&n.deg>0;}).sort(function(a,b){return a.label.localeCompare(b.label);});
  var lone=nodes.filter(function(n){return n.kind==="comp"&&n.deg===0;}).sort(function(a,b){return a.label.localeCompare(b.label);});
  jd.forEach(function(n,i){ var a=i/Math.max(1,jd.length)*Math.PI*2-Math.PI/2; n.x=CX+Math.cos(a)*64; n.y=CY+Math.sin(a)*64; n.r=11; });
  linked.forEach(function(n,i){ var a=i/Math.max(1,linked.length)*Math.PI*2-Math.PI/2; n.x=CX+Math.cos(a)*205; n.y=CY+Math.sin(a)*205; n.r=7; });
  lone.forEach(function(n,i){ var a=i/Math.max(1,lone.length)*Math.PI*2-Math.PI/2; n.x=CX+Math.cos(a)*325; n.y=CY+Math.sin(a)*325; n.r=5.5; });
  function el(tag,attrs){ var e=document.createElementNS(NS,tag); for(var k in attrs) e.setAttribute(k,attrs[k]); return e; }
  FGN.pairs.forEach(function(p){
    var a=byKey[p.a], b=byKey[p.b]; if(!a||!b) return;
    gE.appendChild(el("line",{x1:a.x.toFixed(1),y1:a.y.toFixed(1),x2:b.x.toFixed(1),y2:b.y.toFixed(1),"class":"edge follow"+(p.mutual?" mutual":""),"data-a":p.a,"data-b":p.b}));
  });
  var tip=$("#tip");
  function tipShow(n,ev){
    var s='<b>'+esc(n.kind==="jd"?n.label+" (JD's account)":n.label)+'</b>';
    if(n.kind==="comp") s+=esc(n.comp.town||"")+'<br>'+n.follows.length+' follows, '+n.followedBy.length+' followers (verified links)';
    else s+='JD Meyers Productions account<br>'+n.follows.length+' follows, '+n.followedBy.length+' followers (verified links)';
    tip.innerHTML=s; tip.classList.add("on"); tipMove(ev);
  }
  function tipMove(ev){ tip.style.left=Math.min(window.innerWidth-270,ev.clientX+14)+"px"; tip.style.top=(ev.clientY+14)+"px"; }
  function tipHide(){ tip.classList.remove("on"); }
  function nameLink(n){
    if(n.kind==="jd") return esc(n.label);
    return '<button class="linkish" data-open="'+esc(n.comp.id)+'">'+esc(n.label)+'</button>';
  }
  function select(n){
    $$("#netNodes .node").forEach(function(g){ g.classList.remove("lit"); });
    n.el.classList.add("lit"); wrap.classList.add("focusing");
    $$("#netEdges .edge").forEach(function(e){
      e.classList.toggle("lit", e.getAttribute("data-a")===n.key||e.getAttribute("data-b")===n.key);
    });
    var d=$("#fgDetail"), s='';
    s+='<p style="font-size:17px;margin:0 0 10px"><b>'+(n.kind==="jd"?esc(n.label):'<button class="linkish" data-open="'+esc(n.comp.id)+'" style="font-size:17px">'+esc(n.label)+'</button>')+'</b>'+(n.kind==="comp"&&n.comp.town?'<span class="muted"> \u2014 '+esc(n.comp.town)+'</span>':"")+'</p>';
    s+='<div class="grid g-2">';
    s+='<div><p class="hint" style="margin:0 0 6px">Follows ('+n.follows.length+')</p>'+(n.follows.length?'<p>'+n.follows.map(nameLink).join(", ")+'</p>':'<p class="muted">None verified.</p>')+'</div>';
    s+='<div><p class="hint" style="margin:0 0 6px">Followed by ('+n.followedBy.length+')</p>'+(n.followedBy.length?'<p>'+n.followedBy.map(nameLink).join(", ")+'</p>':'<p class="muted">None verified.</p>')+'</div>';
    s+='</div>';
    if(n.kind==="comp"&&FG.status&&FG.status[n.handle]==="unavailable_via_api")
      s+='<p class="hint" style="margin-top:10px">This account\u2019s full following list has not been mapped yet \u2014 it needs a logged-in Instagram check.</p>';
    d.innerHTML=s;
  }
  nodes.forEach(function(n){
    var g=el("g",{"class":"node "+n.kind,tabindex:"0",role:"button","aria-label":n.kind==="jd"?n.label+" (JD's account)":n.label});
    g.appendChild(el("circle",{r:n.r,fill:n.kind==="jd"?"var(--amber)":"#8fa3c8",stroke:"rgba(10,12,17,.8)","stroke-width":1.2}));
    var t=el("text",{x:n.r+6,y:4,"class":n.deg>0||n.kind==="jd"?"":"lbl-hover"}); t.textContent=n.label; g.appendChild(t);
    n.el=g; gN.appendChild(g);
    g.setAttribute("transform","translate("+n.x.toFixed(1)+","+n.y.toFixed(1)+")");
    g.addEventListener("pointerenter",function(ev){ tipShow(n,ev); });
    g.addEventListener("pointermove",tipMove);
    g.addEventListener("pointerleave",tipHide);
    g.addEventListener("click",function(){ select(n); });
    g.addEventListener("keydown",function(ev){ if(ev.key==="Enter"||ev.key===" "){ ev.preventDefault(); select(n); } });
  });
  return {
    wake:function(){},
    focus:function(id){
      var c=BY_ID[id], n=c&&c.ig_handle?byKey["ig:"+normHandle(c.ig_handle)]:null;
      if(!n) return; select(n); wrap.scrollIntoView({behavior:reduceMotion?"auto":"smooth",block:"center"});
    }
  };
}

/* ============================================================
   MAP: town-level pins
   ============================================================ */
RENDER.map=function(el){
  var groups={}, unmapped=[];
  C.forEach(function(c){
    var canon=TOWNS.aliases[c.town];
    if(!canon||!TOWNS.coords[canon]){ unmapped.push(c.name); return; }
    var g=groups[canon]||(groups[canon]={canon:canon,names:[],regions:{}});
    g.names.push(c.name); g.regions[c.region]=(g.regions[c.region]||0)+1;
  });
  var keys=Object.keys(groups);
  var lats=keys.map(function(k){return TOWNS.coords[k].lat;});
  var lngs=keys.map(function(k){return TOWNS.coords[k].lng;});
  var la0=Math.min.apply(null,lats)-.12, la1=Math.max.apply(null,lats)+.12;
  var ln0=Math.min.apply(null,lngs)-.12, ln1=Math.max.apply(null,lngs)+.12;
  var W=760,H=600,pad=54;
  function X(lng){ return pad+(lng-ln0)/(ln1-ln0)*(W-pad*2); }
  function Y(lat){ return pad+(1-(lat-la0)/(la1-la0))*(H-pad*2); }
  var RC={slc:"#EDEAE2",adjacent:"#7FB2CE",unconfirmed:"#737C8E"};
  var RL={slc:"St. Lawrence County",adjacent:"Neighboring counties",unconfirmed:"Location unconfirmed"};
  var h='<div class="page-head"><h1>Where they are</h1><p>One pin per town \u2014 general area only, not exact addresses. Hover or tap a pin for the businesses there.</p></div>';
  h+='<div class="net-wrap" style="height:min(70vh,640px)"><svg viewBox="0 0 '+W+' '+H+'" role="img" aria-label="Competitor map"><g id="mapPins"></g></svg>'+
     '<div class="net-legend"><span><span class="swatch" style="--c:#EDEAE2;border-radius:50%"></span>St. Lawrence Co.</span><span><span class="swatch" style="--c:#7FB2CE;border-radius:50%"></span>Neighboring counties</span><span><span class="swatch" style="--c:#737C8E;border-radius:50%"></span>Unconfirmed</span><span>'+keys.length+' towns</span></div></div>';
  h+='<div class="panel" style="margin-top:18px"><h2>Towns</h2><p class="hint">'+keys.length+' towns with pins'+(unmapped.length?'; '+unmapped.length+' without a mappable town: '+unmapped.map(esc).join(", "):"")+'.</p><div class="tablewrap"><table class="data"><thead><tr><th>Town</th><th>Businesses</th><th>Names</th></tr></thead><tbody>';
  keys.sort(function(a,b){return groups[b].names.length-groups[a].names.length||a.localeCompare(b);}).forEach(function(k){
    var g=groups[k];
    h+='<tr style="cursor:default"><td class="nm">'+esc(k)+'</td><td class="num">'+g.names.length+'</td><td class="muted">'+g.names.map(esc).join("; ")+'</td></tr>';
  });
  h+='</tbody></table></div></div>';
  el.innerHTML=h;
  var NS="http://www.w3.org/2000/svg", gP=$("#mapPins"), tip=$("#tip");
  function tipMove(ev){ tip.style.left=Math.min(window.innerWidth-280,ev.clientX+14)+"px"; tip.style.top=(ev.clientY+14)+"px"; }
  keys.forEach(function(k){
    var g=groups[k], co=TOWNS.coords[k];
    var reg=Object.keys(g.regions).sort(function(a,b){return g.regions[b]-g.regions[a];})[0]||"unconfirmed";
    var gg=document.createElementNS(NS,"g");
    gg.setAttribute("class","map-pin"); gg.setAttribute("tabindex","0"); gg.setAttribute("role","button");
    gg.setAttribute("aria-label",k+", "+g.names.length+" businesses");
    var c=document.createElementNS(NS,"circle");
    c.setAttribute("cx",X(co.lng).toFixed(1)); c.setAttribute("cy",Y(co.lat).toFixed(1));
    c.setAttribute("r",g.names.length>1?11:8); c.setAttribute("fill",RC[reg]||"#737C8E");
    c.setAttribute("stroke","rgba(10,12,17,.85)"); c.setAttribute("stroke-width","1.5");
    gg.appendChild(c);
    if(g.names.length>1){
      var t=document.createElementNS(NS,"text");
      t.setAttribute("x",X(co.lng).toFixed(1)); t.setAttribute("y",(Y(co.lat)+4).toFixed(1));
      t.setAttribute("text-anchor","middle"); t.textContent=g.names.length; gg.appendChild(t);
    }
    var html='<b>'+esc(k)+'</b>'+esc(RL[reg]||"")+'<br>'+g.names.map(esc).join("<br>");
    gg.addEventListener("pointerenter",function(ev){ tip.innerHTML=html; tip.classList.add("on"); tipMove(ev); });
    gg.addEventListener("pointermove",tipMove);
    gg.addEventListener("pointerleave",function(){ tip.classList.remove("on"); });
    gg.addEventListener("click",function(ev){ tip.innerHTML=html; tip.classList.add("on"); tipMove(ev); });
    gg.addEventListener("keydown",function(ev){ if(ev.key==="Enter"||ev.key===" "){ ev.preventDefault(); tip.innerHTML=html; tip.classList.add("on"); tip.style.left="50%"; tip.style.top="40%"; } });
    gP.appendChild(gg);
  });
};

/* ============================================================
   ROSTER
   ============================================================ */
var RF = {q:"", lane:null, mom:null, region:null, county:null, sort:"momentum", dir:1};
RENDER.roster = function(el){
  var h='<div class="page-head"><h1>Every business on watch</h1><p>Search, filter by lane, momentum or region, and click a row for the full profile.</p></div>';
  h+='<div class="panel"><div class="filters" style="margin-bottom:16px"><input class="search" id="rq" type="search" placeholder="Search name, town, handle, notes"></div>';
  h+='<div class="filters"><span class="lbl">Lane</span>'+LANES.map(function(l){return '<button class="filter" data-f="lane" data-v="'+l.id+'"><span class="sw" style="--c:'+l.color+'"></span>'+esc(l.label)+'</button>';}).join("")+'</div>';
  h+='<div class="filters"><span class="lbl">Momentum</span>'+Object.keys(MOM).map(function(k){return '<button class="filter" data-f="mom" data-v="'+k+'"><span class="sw" style="--c:'+MOM[k].color+'"></span>'+MOM[k].label+'</button>';}).join("")+'</div>';
  h+='<div class="filters"><span class="lbl">Region</span>'+Object.keys(REGION).map(function(k){return '<button class="filter" data-f="region" data-v="'+k+'">'+REGION[k]+'</button>';}).join("")+'</div>';
  h+='<p class="hint" id="rcount" style="margin:16px 0 4px"></p><div class="tablewrap"><table class="data" id="rtable"><thead><tr>'+
     [["name","Business"],["lanes","Lanes"],["momentum","Momentum"],["price","Starting price"],["followers","Followers"],["post","Last post"],["hub","Found via"]].map(function(c){return '<th data-sort="'+c[0]+'">'+c[1]+'</th>';}).join("")+
     '</tr></thead><tbody></tbody></table></div></div>';
  h+='<div class="panel"><h2>Ruled out</h2><p class="hint">Businesses checked and excluded from the roster, with the reason. Kept so they are not re-added by mistake.</p><div class="tablewrap"><table class="data" style="cursor:default"><tbody>'+
     (D.excluded||[]).map(function(x){return '<tr style="cursor:default"><td class="nm">'+esc(x.name)+'</td><td class="muted">'+esc(x.reason)+'</td></tr>';}).join("")+'</tbody></table></div></div>';
  el.innerHTML=h;
  $("#rq").addEventListener("input",function(){ RF.q=this.value.toLowerCase(); drawRoster(); });
  $$("#view-roster [data-f]").forEach(function(b){ b.onclick=function(){ var f=b.dataset.f; RF[f]=RF[f]===b.dataset.v?null:b.dataset.v; syncFilters(); drawRoster(); }; });
  $$("#rtable th").forEach(function(th){ th.onclick=function(){ var s=th.dataset.sort; if(RF.sort===s) RF.dir*=-1; else { RF.sort=s; RF.dir=(s==="followers"||s==="price")?-1:1; } drawRoster(); }; });
  syncFilters(); drawRoster();
};
function syncFilters(){ $$("#view-roster [data-f]").forEach(function(b){ b.setAttribute("aria-pressed", RF[b.dataset.f]===b.dataset.v); }); }
function drawRoster(){
  var list = C.filter(function(c){
    if(RF.lane && c.lanes.indexOf(RF.lane)<0) return false;
    if(RF.mom && c.momentum.k!==RF.mom) return false;
    if(RF.region && c.region!==RF.region) return false;
    if(RF.county && (c.county||"")!==RF.county) return false;
    if(RF.q){ var t=[c.name,c.town,c.ig_handle,c.notes,c.website,c.pricing].join(" ").toLowerCase(); if(t.indexOf(RF.q)<0) return false; }
    return true;
  });
  function key(c){
    switch(RF.sort){
      case "name": return c.name.toLowerCase();
      case "lanes": return c.lanes[0];
      case "momentum": return MOM[c.momentum.k].rank*1e6-(c.postAge==null?-1e5:-c.postAge);
      case "price": return c.price.wedding||c.price.session||(RF.dir<0?-1:1e9);
      case "followers": return c.followers||(RF.dir<0?-1:1e9);
      case "post": return c.postAge==null?1e9:c.postAge;
      case "hub": return HUBS[c.hub].label;
    }
  }
  list.sort(function(a,b){ var x=key(a),y=key(b); return (x<y?-1:x>y?1:0)*RF.dir || a.name.localeCompare(b.name); });
  $$("#rtable th").forEach(function(th){ if(th.dataset.sort===RF.sort) th.setAttribute("aria-sort",RF.dir>0?"ascending":"descending"); else th.removeAttribute("aria-sort"); });
  $("#rcount").textContent = list.length+" of "+C.length+" shown"+(RF.county?" in "+RF.county+" County":"");
  $("#rtable tbody").innerHTML = list.map(function(c){
    var p = c.price.wedding?money(c.price.wedding):c.price.session?money(c.price.session)+' session':(c.price.hourly?'hourly':'<span class="muted">not public</span>');
    return '<tr data-open="'+c.id+'"><td class="nm">'+esc(c.name)+'<small>'+esc(c.town||"")+'</small></td><td>'+laneTags(c)+'</td><td>'+momBadge(c)+'</td><td class="num">'+p+'</td>'+
      '<td class="r">'+(c.followers?fmt(c.followers):'<span class="muted">–</span>')+'</td><td class="num">'+(c.last_post_date?shortDate(c.last_post_date):'<span class="muted">–</span>')+'</td><td class="muted">'+esc(HUBS[c.hub].label)+'</td></tr>';
  }).join("") || '<tr><td colspan="7" class="empty">Nothing matches. Clear a filter to widen the list.</td></tr>';
}

/* ============================================================
   MARKET LANES
   ============================================================ */
RENDER.market = function(el){
  var h='<div class="page-head"><h1>The market, lane by lane</h1><p>How each type of work is shaping up: who is in it, which way it is moving, where prices sit, and how often AI points people to JD.</p></div>';
  h+='<div class="grid g-2">';
  LANES.forEach(function(l){
    var s=LSTATS[l.id]; if(!s.n) return;
    var sorted = s.list.slice().sort(function(a,b){ return MOM[a.momentum.k].rank-MOM[b.momentum.k].rank || a.name.localeCompare(b.name); });
    h+='<div class="panel lanecard" id="lane-'+l.id+'" style="--c:'+l.color+'"><div class="row-between"><h2>'+esc(l.label)+'</h2>'+(l.id==="unclassified"?'':dirLabel(s))+'</div>'+
       (l.id==="unclassified"?'<p class="hint" style="margin-top:6px">No service information yet. Classifying these (a website visit or an IG check) is the fastest way to sharpen the picture.</p>':'')+
       '<div class="stats"><div><b class="num">'+s.n+'</b>tracked</div><div><b class="num">'+s.home+'</b>in St. Lawrence</div>'+
       (s.wMed&&(l.id==="weddings"||l.id==="video")?'<div><b class="num">'+money(s.wMed)+'</b>median wedding start</div>':'')+(s.sMed&&l.id!=="video"&&l.id!=="drone"?'<div><b class="num">'+money(s.sMed)+'</b>median session start</div>':'')+
       (s.ai!=null?'<div><b class="num" style="color:var(--amber)">'+pct(s.ai)+'</b>JD in AI answers</div>':'')+'</div>'+
       mixBar(s.mom,s.n)+'<div class="chips" style="margin-top:14px">'+sorted.map(function(c){return chipFor(c.id);}).join("")+'</div></div>';
  });
  h+='</div>';
  h+='<div class="panel" style="margin-top:18px"><h2>Wedding starting prices</h2><p class="hint">Each dot is a published starting price. The amber line is the median. Hover for the name, click to open.</p><div class="strip" id="stripW"></div>'+
     '<h2 style="margin-top:10px">Portrait and session starting prices</h2><p class="hint">Minis, family, senior and couples sessions.</p><div class="strip" id="stripS"></div></div>';
  el.innerHTML=h;
  priceStrip($("#stripW"), C.filter(function(c){return c.price.wedding;}).map(function(c){return {c:c,v:c.price.wedding};}));
  priceStrip($("#stripS"), C.filter(function(c){return c.price.session;}).map(function(c){return {c:c,v:c.price.session};}));
};
function priceStrip(el, pts){
  if(!pts.length){ el.innerHTML='<p class="empty">No published prices yet.</p>'; return; }
  var W=1000,H=120,pl=20,pr=20,max=Math.max.apply(null,pts.map(function(p){return p.v;})), step=max>2000?1000:100, top=Math.ceil(max*1.08/step)*step;
  function X(v){ return pl+v/top*(W-pl-pr); }
  var g='<g class="axis">';
  for(var t=0;t<=top;t+=step*(top/step>10?2:1)) g+='<line x1="'+X(t)+'" x2="'+X(t)+'" y1="10" y2="'+(H-24)+'" stroke="#242A37"/><text x="'+X(t)+'" y="'+(H-6)+'" text-anchor="middle">'+money(t)+'</text>';
  g+='</g>';
  var med=median(pts.map(function(p){return p.v;}));
  g+='<line x1="'+X(med)+'" x2="'+X(med)+'" y1="4" y2="'+(H-24)+'" stroke="#E7A04F" stroke-width="2"/><text x="'+(X(med)+6)+'" y="14" fill="#E7A04F" font-size="12">median '+money(med)+'</text>';
  var used={};
  pts.sort(function(a,b){return a.v-b.v;}).forEach(function(p){
    var bucket=Math.round(X(p.v)/14); used[bucket]=(used[bucket]||0)+1; var row=used[bucket]-1;
    var y=(H-24)/2+ (row%2?1:-1)*Math.ceil(row/2)*15;
    g+='<circle class="dotp" data-open="'+p.c.id+'" cx="'+X(p.v)+'" cy="'+y+'" r="6.5" fill="'+LANE[p.c.lanes[0]].hex+'" stroke="#0A0C11" stroke-width="1.5"><title>'+esc(p.c.name+": "+money(p.v))+'</title></circle>';
  });
  el.innerHTML='<svg viewBox="0 0 '+W+' '+H+'" preserveAspectRatio="none" role="img" aria-label="Price distribution">'+g+'</svg>';
}

/* ============================================================
   AI VISIBILITY
   ============================================================ */
RENDER.ai = function(el){
  var ENG_COL={"ChatGPT":"#8FD0F5","Claude":"#E7A04F","Gemini":"#A99CE0","Perplexity":"#D595AE"};
  var h='<div class="page-head"><h1>When people ask AI who to hire</h1><p>Five real customer questions go to four AI engines several times a day. This tracks whether JD gets named, and who gets named instead.</p></div>';
  h+='<div class="grid g-2"><div class="panel"><h2>JD named, by engine</h2><p class="hint">Share of answered prompts that named JD. A partial mention counts as half.</p><div class="chart">'+
     lineChart(ENGINES.map(function(e){ return {name:e,color:ENG_COL[e]||"#AAB1BF",values:RUNS.map(function(r){ return rate(r.rows.filter(function(x){return x.engine===e;})); })}; }), {w:560,h:230,labels:RUNS.map(function(r){return r.tick;}),aria:"JD named rate by engine"})+
     '</div><div class="chips" style="margin-top:10px">'+ENGINES.map(function(e){return '<span class="chip" style="--d:'+(ENG_COL[e]||"#AAB1BF")+';cursor:default"><span class="dot"></span>'+esc(e)+'</span>';}).join("")+'</div></div>';
  // heatmap
  h+='<div class="panel"><h2>Latest run, question by question</h2><p class="hint">'+esc(LAST_RUN?LAST_RUN.label:"")+'. Numbers are JD’s position in the answer.</p><div class="tablewrap"><table class="heat"><thead><tr><th>Question</th>'+ENGINES.map(function(e){return '<th>'+esc(e)+'</th>';}).join("")+'</tr></thead><tbody>';
  PROMPTS.forEach(function(p){
    h+='<tr><td class="p">'+esc(p)+'</td>'+ENGINES.map(function(e){
      var r=LAST_RUN?LAST_RUN.rows.filter(function(x){return x.engine===e && x.prompt===p;})[0]:null;
      if(!r||r.jd_named==="unreachable") return '<td class="hc-na" title="Engine unreachable">off</td>';
      var cls=r.jd_named==="yes"?"hc-yes":r.jd_named==="partial"?"hc-partial":"hc-no";
      var txt=r.jd_named==="no"?"no":(r.jd_rank?"#"+r.jd_rank+(r.of_total?" of "+r.of_total:""):"yes");
      return '<td class="'+cls+'">'+txt+'</td>';
    }).join("")+'</tr>';
  });
  h+='</tbody></table></div></div></div>';
  // rivals
  var blind=RIVALS.filter(function(r){return r.status==="blind";}).length;
  h+='<div class="panel" style="margin-top:18px"><h2>Who AI recommends instead</h2><p class="hint">Every business named on '+shortDate(LAST_RUN&&LAST_RUN.date)+', by how many engine answers named them. '+blind+' are blind spots: not on your roster and not ruled out.</p>'+
     '<div class="filters" style="margin-bottom:14px" id="rivF"><button class="filter" data-r="all" aria-pressed="true">All</button><button class="filter" data-r="blind">Blind spots</button><button class="filter" data-r="roster">On roster</button><button class="filter" data-r="excluded">Ruled out</button></div>'+
     '<div class="tablewrap"><table class="data"><thead><tr><th>Business</th><th>Answers</th><th>Engines</th><th>Status</th></tr></thead><tbody id="rivBody"></tbody></table></div></div>';
  el.innerHTML=h;
  function drawRiv(f){
    $("#rivBody").innerHTML=RIVALS.filter(function(r){return f==="all"||r.status===f;}).map(function(r){
      var st=r.status==="roster"?'<span class="status-pill sp-roster">On roster</span>':r.status==="excluded"?'<span class="status-pill sp-excluded" title="'+esc(r.excluded.reason)+'">Ruled out</span>':'<span class="status-pill sp-blind">Blind spot</span>';
      return '<tr'+(r.comp?' data-open="'+r.comp.id+'"':' style="cursor:default"')+'><td class="nm">'+esc(r.name)+(r.excluded?'<small>'+esc(r.excluded.reason)+'</small>':'')+'</td><td class="num">'+r.n+'</td><td class="muted">'+Object.keys(r.engines).join(", ")+'</td><td>'+st+'</td></tr>';
    }).join("")||'<tr><td colspan="4" class="empty">None in this group.</td></tr>';
  }
  $$("#rivF [data-r]").forEach(function(b){ b.onclick=function(){ $$("#rivF [data-r]").forEach(function(x){x.setAttribute("aria-pressed",x===b);}); drawRiv(b.dataset.r); }; });
  drawRiv("all");
};

/* ============================================================
   WEBSITE SWEEPS
   ============================================================ */
RENDER.sweeps = function(el){
  var h='<div class="page-head"><h1>Website sweeps</h1><p>Each run visits competitor websites, saves a snapshot, and compares it to the last one. Changes in pricing, packages or availability show up here.</p></div>';
  var watch = C.filter(function(c){ return c.sweep && c.sweep.status==="unreachable"; });
  h+='<div class="grid g-hero"><div class="panel"><ul class="timeline">';
  SWEEPS.slice().reverse().forEach(function(s){
    var unreach = Object.keys(s.pages||{}).filter(function(k){ return s.pages[k].status==="unreachable"; });
    var changed = Object.keys(s.pages||{}).filter(function(k){ return s.pages[k].status==="changed"; });
    h+='<li><div class="d">'+shortDate(s.date)+'</div><h3>'+esc(s.run_label)+'</h3>'+
      (s.of_total?'<div class="progress"><i style="width:'+(s.fetched/s.of_total*100)+'%"></i></div><div class="muted" style="font-size:13px">'+s.fetched+' of '+s.of_total+' sites reached'+(changed.length?', '+changed.length+' changed':'')+(unreach.length?', '+unreach.length+' unreachable':'')+'</div>':'')+
      (s.summary?'<p style="color:var(--silver-2);font-size:14px;margin:10px 0 0;max-width:70ch">'+esc(s.summary)+'</p>':'')+
      ((s.new_entrants||[]).length?'<div style="margin-top:10px"><span class="muted" style="font-size:12.5px">New entrants</span><div class="chips" style="margin-top:6px">'+s.new_entrants.map(function(n){ var c=findComp(n); return c?chipFor(c.id):'<span class="tag">'+esc(n)+'</span>'; }).join("")+'</div></div>':'')+
      ((s.roster_corrections||[]).length?'<ul class="inner">'+s.roster_corrections.map(function(t){return '<li>'+esc(t)+'</li>';}).join("")+'</ul>':'')+'</li>';
  });
  h+='</ul></div><div class="stack"><div class="panel"><h2>Needs a manual check</h2><p class="hint">Websites that failed on the latest attempt. Repeated failures usually mean a moved or closed site.</p>'+
     (watch.length?'<div class="conn" style="display:flex;flex-direction:column;gap:12px">'+watch.map(function(c){ return '<div><button class="linkish" data-open="'+c.id+'">'+esc(c.name)+'</button><div class="muted" style="font-size:13px">'+esc(c.sweep.note||"unreachable")+'</div></div>'; }).join("")+'</div>':'<p class="empty">All sites reached.</p>')+
     '</div><div class="panel"><h2>Not monitored</h2><p class="hint">'+C.filter(function(c){return !c.website;}).length+' businesses have no website on file, so sweeps cannot watch them.</p><div class="chips">'+C.filter(function(c){return !c.website;}).map(function(c){return chipFor(c.id);}).join("")+'</div></div></div></div>';
  el.innerHTML=h;
};

/* ============================================================
   INTAKE (queue stays in this browser; copy lines to Luna)
   ============================================================ */
var QUEUE_KEY="pulse_intake_queue";
function getQueue(){ try{ return JSON.parse(localStorage.getItem(QUEUE_KEY)||"[]"); }catch(e){ return []; } }
function setQueue(q){ try{ localStorage.setItem(QUEUE_KEY, JSON.stringify(q)); }catch(e){} }
function rosterLine(e){
  var bits=["- "+(e.name||"Unnamed").trim(),(e.specialty||"photo").trim(),(e.town||"TBD").trim(),(e.website||"TBD").trim(),e.ig?("@"+e.ig.trim().replace(/^@/,"")):"IG: TBD"];
  var tail=[]; if(e.source) tail.push("source: "+e.source); if(e.collab) tail.push("collaborated with: "+e.collab); if(e.notes) tail.push(e.notes.trim());
  if(tail.length) bits.push(tail.join("; ")); return bits.join(" | ");
}
RENDER.intake = function(el){
  el.innerHTML='<div class="page-head"><h1>Add a competitor</h1><p>Queue a business you have spotted. The queue stays in this browser until you copy it to Luna, who adds it to the roster on the next sync.</p></div>'+
    '<div class="panel" style="max-width:860px"><div class="formgrid">'+
    '<label class="field"><span>Business name</span><input id="inName" placeholder="Jane Doe Photography"></label>'+
    '<label class="field"><span>Specialty</span><select id="inSpec"><option value="photo">Photo</option><option value="video">Video</option><option value="both">Photo and video</option><option value="drone">Drone</option></select></label>'+
    '<label class="field"><span>Town</span><input id="inTown" placeholder="Potsdam, NY"></label>'+
    '<label class="field"><span>Website</span><input id="inWeb" placeholder="example.com"></label>'+
    '<label class="field"><span>Instagram handle</span><input id="inIG" placeholder="@handle"></label>'+
    '<label class="field"><span>Where you found them</span><select id="inSource"><option>Instagram</option><option>Web search</option><option>Facebook</option><option>Referral</option><option>AI audit</option><option>Client mention</option><option>Other</option></select></label>'+
    '<label class="field full"><span>Worked with (names, comma separated)</span><input id="inCollab" placeholder="Julia Kia Photography, North Country Films"></label>'+
    '<label class="field full"><span>Notes</span><textarea id="inNotes" rows="3" placeholder="Pricing seen, services, status, how you found them"></textarea></label>'+
    '</div><div class="controls"><button class="btn" id="inQueue">Add to queue</button><button class="btn ghost" id="inCopy">Copy queue for Luna</button></div><div id="queueList" style="margin-top:18px"></div></div>';
  function draw(){
    var q=getQueue(), host=$("#queueList");
    if(!q.length){ host.innerHTML='<p class="hint">The queue is empty. Add a business above.</p>'; return; }
    host.innerHTML='<h3>In the queue ('+q.length+')</h3>'+q.map(function(e,i){
      return '<div class="queueitem"><div><b>'+esc(e.name)+'</b> <span class="muted">'+esc(e.town||"")+'</span><div class="muted" style="font-size:12.5px">'+esc(e.source)+', queued '+shortDate(e.queued_at)+'</div></div><button class="btn ghost sm" data-rm="'+i+'">Remove</button></div>';
    }).join("");
    $$("[data-rm]",host).forEach(function(b){ b.onclick=function(){ var qq=getQueue(); qq.splice(+b.dataset.rm,1); setQueue(qq); draw(); }; });
  }
  $("#inQueue").onclick=function(){
    var e={name:$("#inName").value.trim(),specialty:$("#inSpec").value,town:$("#inTown").value.trim(),website:$("#inWeb").value.trim(),ig:$("#inIG").value.trim(),source:$("#inSource").value,collab:$("#inCollab").value.trim(),notes:$("#inNotes").value.trim(),queued_at:new Date().toISOString().slice(0,10)};
    if(!e.name){ $("#inName").focus(); return; }
    var dupe=findComp(e.name);
    if(dupe && !confirm(dupe.name+" is already on the roster. Add anyway?")) return;
    var q=getQueue(); q.push(e); setQueue(q); draw();
    ["inName","inTown","inWeb","inIG","inCollab","inNotes"].forEach(function(id){ $("#"+id).value=""; });
  };
  $("#inCopy").onclick=function(){
    var txt=getQueue().map(rosterLine).join("\n")||"(queue is empty)", b=$("#inCopy");
    function done(ok){ b.textContent=ok?"Copied":"Copy failed, select manually"; setTimeout(function(){ b.textContent="Copy queue for Luna"; },1800); }
    if(navigator.clipboard&&navigator.clipboard.writeText) navigator.clipboard.writeText(txt).then(function(){done(true);},function(){done(false);});
    else { var ta=document.createElement("textarea"); ta.value=txt; document.body.appendChild(ta); ta.select(); try{ document.execCommand("copy"); done(true);}catch(err){ done(false);} document.body.removeChild(ta); }
  };
  draw();
};

/* ============================================================
   DETAIL DRAWER
   ============================================================ */
var drawer=$("#drawer"), scrim=$("#scrim"), lastFocus=null;
function openDetail(id){
  var html = BY_ID[id]?compDetail(BY_ID[id]) : HUBS[id]?hubDetail(HUBS[id]) : EXT[id]?extDetail(EXT[id]) : id==="jd"?jdDetail() : null;
  if(!html) return;
  lastFocus=document.activeElement;
  $("#drawerBody").innerHTML=html;
  drawer.scrollTop=0;
  scrim.hidden=false; requestAnimationFrame(function(){ scrim.classList.add("on"); drawer.classList.add("on"); });
  drawer.setAttribute("aria-hidden","false"); drawer.focus();
  var sp=$("#followSpark"); if(sp && BY_ID[id] && BY_ID[id].followHist) sp.innerHTML=followChart(BY_ID[id].followHist);
}
function closeDetail(){
  drawer.classList.remove("on"); scrim.classList.remove("on"); drawer.setAttribute("aria-hidden","true");
  setTimeout(function(){ scrim.hidden=true; },260);
  if(lastFocus && lastFocus.focus) lastFocus.focus();
}
function relList(id){
  var ls=linksOf(id);
  if(!ls.length) return '<p class="muted" style="font-size:13.5px">No recorded collaborations yet.</p>';
  return '<div class="conn">'+ls.map(function(l){ var o=l.s===id?l.t:l.s; return '<div><button class="linkish" data-open="'+esc(o)+'">'+esc(nameOf(o))+'</button> <span class="muted">'+esc(SUB_LABEL[l.sub]||l.sub)+(l.date?", "+shortDate(l.date):"")+'</span><div class="muted" style="font-size:12.5px;margin-top:2px">'+esc(l.evidence||"")+'</div></div>'; }).join("")+'</div>';
}
function flagText(f){
  var m;
  if((m=/^(\d+)-google-reviews(?:-(\d)-(\d))?$/.exec(f))) return m[1]+" Google reviews"+(m[2]?" ("+m[2]+"."+m[3]+")":"");
  if((m=/^(knot|zola)-(\d)-(\d)-(\d+)-reviews?$/.exec(f))) return (m[1]==="knot"?"The Knot":"Zola")+" "+m[2]+"."+m[3]+" ("+m[4]+" reviews)";
  if((m=/^fb-(\d+)-reviews-(\d+)pct$/.exec(f))) return m[1]+" Facebook reviews, "+m[2]+"% positive";
  if((m=/^new-entrant-(.+)$/.exec(f))) return "New entrant "+shortDate(m[1]);
  var map={"faa-part-107":"FAA Part 107","llc-2022":"LLC since 2022","nnypp-member":"NNY Professional Photographers member","vouched-by-jd":"Vouched by JD","ig-dormant-placeholder":"Placeholder IG account, ignore","mutual-ig-follows-jd":"Mutual follow with JD"};
  if(map[f]) return map[f];
  var s=f.replace(/-/g," "); return s.charAt(0).toUpperCase()+s.slice(1);
}
function compDetail(c){
  var m=MOM[c.momentum.k], hb=HUBS[c.hub], isHub=HUB_LIST.filter(function(h){return h.seed===c.id;})[0];
  var h='<h2>'+esc(c.name)+'</h2><div class="sub">'+esc(c.town||"Town unknown")+'</div><div>'+laneTags(c)+'</div>';
  h+='<div class="momo" style="--c:'+m.color+';margin-top:14px"><b>'+m.label+'.</b> '+esc(c.momentum.why)+'</div>';
  h+='<dl class="facts">';
  h+='<dt>Region</dt><dd>'+esc(REGION[c.region]||c.region)+(c.county&&c.county!=="unknown"&&c.region!=="slc"?", "+esc(c.county)+" County":"")+'</dd>';
  h+='<dt>Work</dt><dd>'+esc({photo:"Photography",video:"Videography",both:"Photo and video",drone:"Drone"}[c.specialty]||c.specialty)+'</dd>';
  h+='<dt>Pricing</dt><dd>'+(c.pricing?esc(c.pricing)+(c.pricing_url?' <a href="'+esc(url(c.pricing_url))+'" target="_blank" rel="noopener">source</a>':''):'<span class="muted">Not published</span>')+'</dd>';
  h+='<dt>Website</dt><dd>'+(c.website?'<a href="'+esc(url(c.website))+'" target="_blank" rel="noopener">'+esc(c.website)+'</a>':'<span class="muted">None on file</span>')+'</dd>';
  h+='<dt>Instagram</dt><dd>'+(c.ig_handle?'<a href="https://instagram.com/'+esc(c.ig_handle)+'" target="_blank" rel="noopener">@'+esc(c.ig_handle)+'</a>'+(c.followers?', '+fmt(c.followers)+' followers':''):'<span class="muted">None on file</span>')+'</dd>';
  h+='<dt>Last post</dt><dd>'+(c.last_post_date?shortDate(c.last_post_date)+' ('+ago(c.last_post_date)+')'+(c.last_post_topic?'<div class="muted">'+esc(c.last_post_topic)+(c.last_post_type?", "+esc(c.last_post_type):"")+'</div>':''):'<span class="muted">Unknown</span>')+'</dd>';
  h+='<dt>Found via</dt><dd><button class="linkish" data-open="'+esc(hb.seed||hb.id)+'">'+esc(hb.label)+'</button>'+(c.discovered_date?' <span class="muted">on '+shortDate(c.discovered_date)+'</span>':'')+'</dd>';
  h+='<dt>AI mentions</dt><dd>'+(c.aiMentions?'Named in '+c.aiMentions+' AI answers across all runs':'<span class="muted">Never named by AI</span>')+'</dd>';
  if(c.may2026_web_score!=null) h+='<dt>May web score</dt><dd>'+c.may2026_web_score+'</dd>';
  h+='</dl>';
  if(c.followHist && c.followHist.length>1) h+='<section><h3>Followers over time</h3><div class="chart" id="followSpark"></div></section>';
  if(isHub) h+='<section><h3>This account is a hub. Its following surfaced '+isHub.spokes.length+' businesses</h3><div class="chips">'+isHub.spokes.map(chipFor).join("")+'</div></section>';
  h+='<section><h3>Connections</h3>'+relList(c.id)+'</section>';
  if(c.sweep) h+='<section><h3>Website monitor</h3><div class="note">'+esc(c.sweep.status.charAt(0).toUpperCase()+c.sweep.status.slice(1))+' on '+shortDate(c.sweep.date)+(c.sweep.note?'. '+esc(c.sweep.note):'')+'</div></section>';
  if((c.flags||[]).length) h+='<section><h3>Signals</h3><div>'+c.flags.map(function(f){return '<span class="tag">'+esc(flagText(f))+'</span>';}).join("")+'</div></section>';
  if(c.notes) h+='<section><h3>Research notes</h3><div class="note">'+esc(c.notes)+'</div></section>';
  h+='<section><button class="btn ghost sm" data-focus="'+esc(isHub?c.id:c.id)+'">Show on network</button></section>';
  return h;
}
function hubDetail(hb){
  var m={entering:0,active:0,quiet:0,fading:0,unknown:0}; hb.spokes.forEach(function(id){ m[BY_ID[id].momentum.k]++; });
  var h='<h2>'+esc(hb.label)+'</h2><div class="sub">'+esc(hb.kind)+'</div><p class="note">'+esc(hb.desc)+'</p>';
  h+='<dl class="facts"><dt>Surfaced</dt><dd>'+hb.spokes.length+' businesses</dd><dt>Momentum</dt><dd>'+mixBar(m,hb.spokes.length)+'</dd></dl>';
  h+='<section><h3>Businesses</h3><div class="chips">'+hb.spokes.map(chipFor).join("")+'</div></section>';
  h+='<section><button class="btn ghost sm" data-focus="'+esc(hb.id)+'">Show on network</button></section>';
  return h;
}
function extDetail(x){
  return '<h2>'+esc(x.name)+'</h2><div class="sub">Not on the roster</div><p class="note">This business appears only as a collaborator. If it works in the North Country, consider adding it.</p><section><h3>Connections</h3>'+relList(x.id)+'</section>'+
    '<section><button class="btn ghost sm" data-go="intake">Add as competitor</button></section>';
}
function jdDetail(){
  var h='<h2>JD Meyers Productions</h2><div class="sub">Potsdam, NY. Photo, video and FAA Part 107 drone.</div><dl class="facts">';
  Object.keys(OWN).forEach(function(a){ h+='<dt>@'+esc(a)+'</dt><dd>'+fmt(OWN[a].follower_count)+' followers</dd>'; });
  h+='<dt>AI visibility</dt><dd>'+pct(LAST_RUN?rate(LAST_RUN.rows):null)+' latest run</dd></dl><section><h3>Ties</h3>'+relList("jd")+'</section>';
  return h;
}
function followChart(hist){
  var W=440,H=90,v=hist.map(function(x){return x.count;}), lo=Math.min.apply(null,v), hi=Math.max.apply(null,v); if(hi===lo){ hi+=5; lo-=5; }
  var pts=hist.map(function(x,i){ return [20+i*(W-40)/(hist.length-1), 12+(1-(x.count-lo)/(hi-lo))*(H-36)]; });
  return '<svg viewBox="0 0 '+W+' '+H+'"><path d="M'+pts.map(function(p){return p[0]+","+p[1];}).join(" L")+'" stroke="#DCE0E8" stroke-width="2" fill="none"/>'+
    pts.map(function(p,i){ return '<circle cx="'+p[0]+'" cy="'+p[1]+'" r="3" fill="#DCE0E8"/><text x="'+p[0]+'" y="'+(H-4)+'" text-anchor="middle">'+shortDate(hist[i].date)+'</text><text x="'+p[0]+'" y="'+(p[1]-7)+'" text-anchor="middle" fill="#AAB1BF">'+fmt(hist[i].count)+'</text>'; }).join("")+'</svg>';
}

/* ============================================================
   global wiring
   ============================================================ */
document.addEventListener("click",function(ev){
  var t=ev.target.closest("[data-open],[data-go],[data-focus],[data-lane],[data-mom],[data-county]");
  if(!t || t.closest(".net-wrap svg")) return;
  if(t.hasAttribute("data-open")){ ev.preventDefault(); openDetail(t.getAttribute("data-open")); return; }
  if(t.hasAttribute("data-go")){ closeDetail(); go(t.getAttribute("data-go")); return; }
  if(t.hasAttribute("data-focus")){ var id=t.getAttribute("data-focus"); closeDetail(); go("network"); setTimeout(function(){ if(NET) NET.focus(id); },60); return; }
  if(t.hasAttribute("data-lane")){ go("market"); setTimeout(function(){ var x=$("#lane-"+t.getAttribute("data-lane")); if(x) x.scrollIntoView({behavior:reduceMotion?"auto":"smooth",block:"start"}); },60); return; }
  if(t.hasAttribute("data-mom")){ RF.mom=t.getAttribute("data-mom"); RF.lane=RF.region=RF.county=null; if(rendered.roster){ syncFilters(); drawRoster(); } go("roster"); return; }
  if(t.hasAttribute("data-county")){ var cn=t.getAttribute("data-county"); RF.county=cn==="Unconfirmed"?null:cn; RF.region=cn==="Unconfirmed"?"unconfirmed":null; RF.mom=RF.lane=null; if(rendered.roster){ syncFilters(); drawRoster(); } go("roster"); return; }
});
document.addEventListener("keydown",function(ev){
  if(ev.key==="Escape" && drawer.classList.contains("on")) closeDetail();
  if(ev.key==="Enter" && ev.target.matches("tr.lane-row")) ev.target.click();
});
scrim.addEventListener("click",closeDetail);
$("#drawerClose").addEventListener("click",closeDetail);
window.addEventListener("hashchange",route);
buildNav(); route();

})();
